export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const TOGGLE_TODO_ITEM_COMPLETION_SUCCESS = 'TOGGLE_TODO_ITEM_COMPLETION_SUCCESS';
export const FETCH_TODO_ITEMS_START = 'FETCH_TODO_ITEMS_START';
export const FETCH_TODO_ITEMS_SUCCESS = 'FETCH_TODO_ITEMS_SUCCESS';
export const FETCH_TODO_ITEMS_FAIL = 'FETCH_TODO_ITEMS_FAIL';