export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const TOGGLE_TODO_ITEM_COMPLETION_SUCCESS = 'TOGGLE_TODO_ITEM_COMPLETION_SUCCESS';
export const FETCH_TODO_ITEMS_START = 'FETCH_TODO_ITEMS_START';
export const FETCH_TODO_ITEMS_SUCCESS = 'FETCH_TODO_ITEMS_SUCCESS';
export const FETCH_TODO_ITEMS_FAIL = 'FETCH_TODO_ITEMS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'LOG_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';




